#EXPLORING THE SALES TABLE
SELECT *
FROM SALES;

#looking at the sale's Amount that is more than USD 10,000

SELECT * 
FROM SALES
WHERE AMOUNT >= 15000
 ORDER BY AMOUNT;
 
 # SALES THAT ARE ABOVE 10K IN THE G1 LOCATION BY YEAR 2022
SELECT *
FROM SALES
WHERE GEOID = 'G1' AND AMOUNT > 10000 AND SALEDATE >= '2022-01-01'
ORDER BY SALEDATE;

# ANOTHER METHOD TO GET THAT ABOVE QUERY BUT USING THE YEAR FUNCTION
SELECT *
FROM SALES 
WHERE GEOID = 'G1' AND AMOUNT > 10000 AND YEAR(SALEDATE) >= 2022
ORDER BY SALEDATE;

# FILTER THE SALES DATA  WHERE THE BOXES ARE BETWEEN 0 AND 50

SELECT *
FROM SALES
WHERE BOXES BETWEEN 0 AND 50
ORDER BY BOXES;

# DISPLAY ALL THE SALES THAT HAPPENED ON FRIDAY
SELECT *, DAYNAME(SALEDATE) AS WEEK_NAME
FROM SALES
WHERE DAYNAME(SALEDATE) = 'Friday';

#Print details of shipments (sales) where amounts are > 2,000 and boxes are <100
SELECT *
FROM SALES
WHERE AMOUNT > 2000 AND BOXES <100;

#2. How many shipments (sales) each of the sales persons had in the month of January 2022?

SELECT P.SALESPERSON, COUNT(S.BOXES) AS Number_of_shipments
FROM SALES S
INNER JOIN PEOPLE P
ON S.SPID = P.SPID
WHERE MONTH(SALEDATE) = 1 AND YEAR(SALEDATE) = 2022
GROUP BY P.SALESPERSON;

#3. Which product sells more boxes? Milk Bars or Eclairs?

SELECT PRD.PRODUCT, sum(S.BOXES) AS TOTAL_BOXES
FROM SALES S
INNER JOIN PRODUCTS PRD
ON S.PID = PRD.PID
WHERE PRD.PRODUCT IN ('Milk bars', 'Eclairs')
GROUP BY PRD.PRODUCT
ORDER BY 2 DESC;

#4. Which product sold more boxes in the first 7 days of February 2022? Milk Bars or Eclairs?

SELECT PRD.PRODUCT, sum(S.BOXES) AS TOTAL_BOXES
FROM SALES S
INNER JOIN PRODUCTS PRD
ON S.PID = PRD.PID
WHERE PRD.PRODUCT IN ('Milk bars', 'Eclairs') AND S.SALEDATE BETWEEN '2022-02-01' AND '2022-02-07'
GROUP BY PRD.PRODUCT
ORDER BY 2 DESC;

#5. Which shipments had under 100 customers & under 100 boxes? Did any of them occur on Wednesday?

SELECT *, dayname(SALEDATE) AS NAME_OF_THE_DAY
FROM SALES
WHERE CUSTOMERS < 100 AND BOXES < 100 AND dayname(saledate) = 'Wednesday'
ORDER BY SALEDATE;

#1.names of salespersons who had at least one shipment (sale) in the first 7 days of January 2022?

SELECT  S.SPID, P.SALESPERSON, COUNT(BOXES) AS TOTAL_SHIPMENT
FROM SALES S
INNER JOIN PEOPLE P
ON S.SPID = P.SPID
WHERE S.SALEDATE BETWEEN '2022-01-01' AND '2022-01-07'
GROUP BY P.SALESPERSON,S.SPID
HAVING COUNT(BOXES) >= 1;

#2. Which salespersons did not make any shipments in the first 7 days of January 2022?

SELECT   SALESPERSON
FROM PEOPLE
WHERE SPID NOT IN ( SELECT SPID FROM SALES
WHERE SALEDATE BETWEEN '2022-01-01' AND '2022-01-07');

#3. How many times we shipped more than 1,000 boxes in each month?

SELECT YEAR(SALEDATE) AS YEARS, MONTH(SALEDATE) AS MONTHS, COUNT(*) TOTAL_SHIPMENTS
FROM SALES
WHERE BOXES > 1000
GROUP BY YEAR(SALEDATE), MONTH(SALEDATE);

#4. Did we ship at least one box of ‘After Nines’ to ‘New Zealand’ on all the months?

SELECT S.GEOID, G.GEO, YEAR(S.SALEDATE) YEARS, MONTH(SALEDATE) MONTHS, COUNT(S.GEOID) AS NUM_OF_BOXES
FROM SALES S
INNER JOIN PRODUCTS PD
ON S.PID = PD.PID
INNER JOIN GEO G
ON S.GEOID = G.GEOID
WHERE G.GEO = 'NEW ZEALAND' AND PD.PRODUCT = 'AFTER NINES'
GROUP BY S.GEOID, G.GEO, YEAR(SALEDATE), MONTH(SALEDATE)
ORDER BY 3,4;

#5. India or Australia? Who buys more chocolate boxes on a monthly basis?

SELECT G.GEO,YEAR(S.SALEDATE) YEARS, MONTH(S.SALEDATE) MONTHS, SUM(S.BOXES) AS TOTAL_BOXES
FROM SALES S
INNER JOIN PRODUCTS PD
ON S.PID = PD.PID
INNER JOIN GEO G
ON S.GEOID = G.GEOID
WHERE G.GEO IN ('INDIA', 'AUSTRALIA') 
GROUP BY YEAR(S.SALEDATE), MONTH(S.SALEDATE), G.GEO
ORDER BY TOTAL_BOXES DESC;


